### PR TITLE
#242 - Correcting top layout constraints

### PR DESCRIPTION
**Pull request by rstewart22**
With the new top layout/margin behaviours, the top "nav bar" would appear below the status bar.

Corrected the constraints to ensure the nav bar covers behind the status bar area. Tested on iPhone 7, but should also fix the problem as reported on iPhone X.

### CODE REVIEW

**Comment by nkezhaya** [comment]
I'll be looking at this soon. Thanks for the PR!

**Comment by nkezhaya** [comment]
@rstewart22 Can you remove your `print()` debug calls from your PR?

**Comment by rstewart22** [comment]
@whitepaperclip  Sorry I have made changes since this PR on this branch that shouldn't be merged for some custom functionality. I'll close this for now and make a branch and a new PR.

**Comment by nkezhaya** [comment]
@rstewart22 No problem, thanks. FYI I'm pushing a pretty substantial change to migrate everything over to Swift 4.2.

I created a stale branch for Swift 3, and I guess we're going to skip over Swift 4.0/4.1.

**Comment by nkezhaya** [comment]
@rstewart22 I'm probably going to move to just using a plain navigation controller. That should fix all iPhone X-related issues.

**Pull request closed without merging**
