### PR TITLE
Swift 4 compatibilty

### PR DESCRIPTION
**Pull request by michaelhenry**

### CODE REVIEW

**Comment by ytakzk** [comment]
@michaelhenry Thank you for the pull request but the build failed. Could you fix that?
https://travis-ci.org/ytakzk/Fusuma/builds/312273771?utm_source=github_status&utm_medium=notification

**Comment by michaelhenry** [comment]
@ytakzk  sure. :D

**Comment by michaelhenry** [comment]
@ytakzk I will also include this #239 to my merge request

**Comment by ytakzk** [comment]
@michaelhenry Thanks 👍

**Comment by michaelhenry** [comment]
@ytakzk thanks 👍

**Pull request merged**
