### PR TITLE
handle error if camera returns null

### PR DESCRIPTION
**Pull request by aterite**
if captureStillImageAsynchronously returns error jpegStillImageNSDataRepresentation(buffer) can throw exception

### CODE REVIEW

**Comment by ytakzk** [comment]
@aterite Is it possible not to use ```else if``` because it creates a deep nest? 
Below is fine.

```
if error != nil {
     self.session?.stopRunning()
     print("Error: \(error!.localizedDescription)")
     return
}
```

**Comment by aterite** [comment]
Yes, It's fine, also guard else can be more readable then
guard error == nil else {
     self.session?.stopRunning()
     print("Error: \(error!.localizedDescription)")
     return
}

**Comment by ytakzk** [comment]
@aterite when you replace that, give me the commit here. then I will merge this.

**Comment by ytakzk** [comment]
Since I have no response, I will close this for now.

**Pull request closed without merging**
