### PR TITLE
Allowed not cropped photos

### PR DESCRIPTION
**Pull request by pixelskull**
This is the requested enhancement in issue [#32](https://github.com/ytakzk/Fusuma/issues/32)

Implemented global variable fusumaCropImage of type Bool and check
in FusumaViewController.doneButtonPressed() and FSCameraView.shotButtonPressed().
By setting fusumaCropImage to false you disable the cropping.

### CODE REVIEW

**Comment by pixelskull** [comment]
This is the requested enhancement in issue [#32](https://github.com/ytakzk/Fusuma/issues/32)

**Comment by ytakzk** [comment]
@pixelskull Thanks!
It will conflict with the current master codebase because I merged another pull request now. Could you pull them and resolve those conflicts?

**Comment by pixelskull** [comment]
@ytakzk ok, I will take the current master. Is there any need for deactivating cropping in Video mode?

**Comment by ytakzk** [comment]
@pixelskull Yes, it would be nice if the developer can choose if he activates cropping or not.

**Comment by pixelskull** [comment]
@ytakzk sorry, I tried some possibilities for Video cropping but didn't found a good solution. I will wrap my head around this over the week. 

By the way, the Views (gallery, camera and video) have some issues with landscape mode (it's some autolayout constrain problem). Is someone working on this topic? I will open an issue on this one.

**Pull request merged**
