### PR TITLE
video recording

### PR DESCRIPTION
**Pull request by waterskier2007**
this is a requested enhancement in issue #4

### CODE REVIEW

**Comment by waterskier2007** [comment]
Right now it returns a local url of the video file. Not sure what the end goal is, but this should help.

**Comment by ytakzk** [comment]
@waterskier2007 Thanks! However, I just updated the project structure today. It could conflict with your codes so could you add the video mode you just wrote to the current codebase, if possible?
If difficult, I will do that.

**Comment by waterskier2007** [comment]
Definitely. I can do that

**Comment by Withney** [comment]
This branch conflicts not resolved.

This branch has conflicts that must be resolved
Only those with write access to this repository can merge pull requests.

**Comment by ytakzk** [comment]
@Withney I will refer this pull request and surely add the video mode.

**Comment by xeravim** [comment]
how is it then? any news about this awesome video feature? :)

**Comment by michaelbina** [comment]
Also checking on this.  Would love this feature as well...

**Pull request merged**
