### PR TITLE
fix for issue #9 and #10 and #12

### PR DESCRIPTION
**Pull request by waterskier2007**

### CODE REVIEW

**Comment by waterskier2007** [comment]
Ignore the work on tintColors. I wasn't using the tintColors correctly. Only total changes that exist are for fixing issues with the button images not looking in the correct bundle.

**Comment by waterskier2007** [comment]
Also fixed issue #12

**Comment by waterskier2007** [comment]
There's also code to make fusumaDismissedWithImage optional as it is redundant with the other delegate method. I suppose you could make both of them optional and the developer could choose which to implement. That or change fusumaDismissedWithImage to fusumaDismissed() so that they just get notified when the picker is dismissed.

**Comment by ytakzk** [comment]
@waterskier2007 Yes, as you said, fusumaDismissedWithImage should be optional. Thanks a lot!

**Pull request merged**
